# Informações básicas para todas as VMs
admin_group: "ifpb"
timezone: "America/Recife"
ntp_server: "pool.ntp.br"

# Configurações do Desenvolvedor (Individual)
u_name: "victor"
domain_name: "victor.devops"

# Endereços IP da Infraestrutura (Matrícula final 14)
arq_ip: "192.168.56.114"
db_ip: "192.168.56.115"
app_ip: "192.168.56.116"
network_cidr: "192.168.56.0/24"

# Configurações NFS (compartilhadas)
nfs_share_path: "/dados/nfs"
nfs_user: "nfs-ifpb"
nfs_mount_path: "/var/nfs"
